(package "sideline-blame"
         "0.1.0"
         "Show blame messages with sideline")

(website-url "https://github.com/emacs-sideline/sideline-blame")
(keywords "sideline" "blame")

(package-file "sideline-blame.el")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "29")
(depends-on "sideline")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
